//
//  MatchState.swift
//  Tompero
//
//  Mutable per-match bookkeeping. Pulled out of GameScene so the scene
//  can shrink to a thin orchestrator. No SpriteKit imports — this is just
//  data + a small set of named mutations the scene + adapter call.
//

import Foundation

final class MatchState {

    /// Active orders shown on the order list. Mirror between host and joiners.
    var orders: [Order] = []

    /// Total orders generated by the host this match (used to number them).
    var orderCount: Int = 0

    /// Host-only spawn counter (ticks in `update(_:)`).
    var orderGenerationCounter: Int = 3 * 60

    /// Final per-match statistics, populated by the host at didMove.
    var matchStatistics: MatchStatistics?

    /// Coins earned by this device this match. Drives the HUD label.
    var totalPoints: Int = 0

    /// Flips true the first time an order appears. Gates the menu→game music
    /// transition + the "order up" SFX vs. the silent first-spawn.
    var firstOrder: Bool = false

    /// The match clock starts the first time an order is generated.
    var timerStarted: Bool = false

    /// True once the under-15s warning SFX has played, so it only plays once.
    var endTimerPlayed: Bool = false

    /// True once the times-up SFX has played.
    var timesUpPlayed: Bool = false

    /// True once `endMatch` has run. The network adapter guards every
    /// dispatch on this so a late `.statistics` payload (host times up
    /// before the broadcast finishes round-tripping) can't re-enter
    /// `endMatch` from the joiner side.
    var ended: Bool = false

    /// Set by an inbound `.pauseRequest(true)` and cleared by
    /// `.pauseRequest(false)`. `GameScene.update(_:)` short-circuits while
    /// this is true so the clock + order generator stop ticking.
    var paused: Bool = false

    /// Per-action tally for the local player this match. Incremented from
    /// the station nodes via `MatchSceneRouting.recordAction(_:)` and read
    /// at match end so per-player awards can be computed.
    var myActions: PlayerAwardStats = .zero

    /// Awards received from peers during the post-match award broadcast.
    /// Populated by `MatchNetworkAdapter.didReceivePlayerAwards`.
    var peerAwards: [String: PlayerAwardStats] = [:]

    // MARK: - Mutations

    func appendOrder(_ order: Order) {
        orderCount += 1
        order.number = orderCount
        orders.append(order)
        matchStatistics?.totalGeneratedOrders += 1
    }

    func removeOrder(at index: Int) {
        guard orders.indices.contains(index) else { return }
        orders.remove(at: index)
    }

    func recordDelivery(coins: Int) {
        matchStatistics?.totalDeliveredOrders += 1
        matchStatistics?.totalPoints += coins
        totalPoints += coins
    }

    func resetSpawnCounter() {
        orderGenerationCounter = 0
    }
}
